server:
  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
    - type: http
      port: 8081

# Task settings
jobs:
  rateUpdaterTask: 5s

# Logging settings.
logging:
  level: INFO
  appenders:
    - type: console
      target: stdout